/**
 * Files that are attached rather than written.
 *
 * A transcript is asked for by a third of the forms anybody fills in and
 * generated by none of them, so it had nowhere to live: the save holds text
 * this program composes and text it learns from, and a PDF from a registrar
 * is neither. Keeping it here means the one folder this app tells you to
 * point an upload dialog at holds everything that dialog will ask for.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import request from 'supertest';
import express from 'express';
import { createApi } from '../src/server/api.js';
import { Repo } from '../src/git/repo.js';
import { syncCurrent } from '../src/model/current.js';
import { makeTempStore, type TempStore } from './helpers.js';

let t: TempStore;
let app: express.Express;

beforeEach(() => {
  t = makeTempStore();
  app = express();
  app.use(express.json({ limit: '32mb' }));
  app.use('/api', createApi({ store: t.store, repo: Repo.forStore(t.store.root) }));
});
afterEach(() => t.cleanup());

const pdf = (text: string) => Buffer.from(`%PDF-1.7\n${text}\n`).toString('base64');

describe('keeping a transcript in the save', () => {
  it('stores it under the name it will be uploaded as, and hands it back', async () => {
    const made = await request(app)
      .post('/api/documents')
      .send({ name: 'Transcript.pdf', data: pdf('a transcript') })
      .expect(200);
    expect(made.body).toMatchObject({ name: 'Transcript.pdf' });
    expect(made.body.bytes).toBeGreaterThan(0);

    const listed = await request(app).get('/api/documents').expect(200);
    expect(listed.body.documents.map((d: { name: string }) => d.name)).toEqual(['Transcript.pdf']);

    const bytes = await request(app).get('/api/documents/Transcript.pdf/file').expect(200);
    expect(bytes.headers['content-type']).toContain('application/pdf');
    expect(bytes.body.toString()).toContain('a transcript');
  });

  /*
   * The point of the whole thing: it is in the folder the upload dialog is
   * pointed at, beside the built resume, without anybody copying it there.
   */
  it('puts it in the flat upload folder, without an application in flight', async () => {
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('t') }).expect(200);
    const folder = syncCurrent(t.store);
    expect(folder.files).toContain('Transcript.pdf');
    expect(fs.existsSync(path.join(folder.dir, 'Transcript.pdf'))).toBe(true);
    // And it is nobody's application, so it does not invent one in the count.
    expect(folder.applications).toBe(0);
  });

  it('takes it out of the folder again when it is removed', async () => {
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('t') }).expect(200);
    expect(syncCurrent(t.store).files).toContain('Transcript.pdf');

    await request(app).delete('/api/documents/Transcript.pdf').expect(200);
    const after = syncCurrent(t.store);
    expect(after.files).not.toContain('Transcript.pdf');
    expect(fs.existsSync(path.join(after.dir, 'Transcript.pdf'))).toBe(false);
  });

  it('refuses a name that is a path, like every other name in the save', async () => {
    const refused = await request(app)
      .post('/api/documents')
      .send({ name: '../config.yaml', data: pdf('not this') })
      .expect(400);
    expect(refused.body.error).toMatch(/not allowed/i);
    expect(t.store.loadConfig().ai).toBeDefined();
  });

  it('says plainly when a document is not there', async () => {
    const missing = await request(app).get('/api/documents/Nothing.pdf/file').expect(404);
    expect(missing.body.error).toMatch(/not in this save/i);
  });

  it('saving the same name again replaces it, which is how renaming works', async () => {
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('old') }).expect(200);
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('new') }).expect(200);
    expect(t.store.listDocuments()).toHaveLength(1);
    expect(t.store.readDocument('Transcript.pdf')?.toString()).toContain('new');
  });
});
