/**
 * Files that are attached rather than written.
 *
 * A transcript is asked for by a third of the forms anybody fills in and
 * generated by none of them, so it had nowhere to live: the save holds text
 * this program composes and text it learns from, and a PDF from a registrar
 * is neither. Keeping it here means the one folder this app tells you to
 * point an upload dialog at holds everything that dialog will ask for.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import request from 'supertest';
import express from 'express';
import { createApi } from '../src/server/api.js';
import { Repo } from '../src/git/repo.js';
import { syncCurrent } from '../src/model/current.js';
import { makeTempStore, type TempStore } from './helpers.js';

let t: TempStore;
let app: express.Express;

beforeEach(() => {
  t = makeTempStore();
  app = express();
  app.use(express.json({ limit: '32mb' }));
  app.use('/api', createApi({ store: t.store, repo: Repo.forStore(t.store.root) }));
});
afterEach(() => t.cleanup());

const pdf = (text: string) => Buffer.from(`%PDF-1.7\n${text}\n`).toString('base64');

describe('keeping a transcript in the save', () => {
  it('stores it under the name it will be uploaded as, and hands it back', async () => {
    const made = await request(app)
      .post('/api/documents')
      .send({ name: 'Transcript.pdf', data: pdf('a transcript') })
      .expect(200);
    expect(made.body).toMatchObject({ name: 'Transcript.pdf' });
    expect(made.body.bytes).toBeGreaterThan(0);

    const listed = await request(app).get('/api/documents').expect(200);
    expect(listed.body.documents.map((d: { name: string }) => d.name)).toEqual(['Transcript.pdf']);

    const bytes = await request(app).get('/api/documents/Transcript.pdf/file').expect(200);
    expect(bytes.headers['content-type']).toContain('application/pdf');
    expect(bytes.body.toString()).toContain('a transcript');
  });

  /*
   * The point of the whole thing: it is in the folder the upload dialog is
   * pointed at, beside the built resume, without anybody copying it there.
   */
  it('puts it in the flat upload folder, without an application in flight', async () => {
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('t') }).expect(200);
    const folder = syncCurrent(t.store);
    expect(folder.files).toContain('Transcript.pdf');
    expect(fs.existsSync(path.join(folder.dir, 'Transcript.pdf'))).toBe(true);
    // And it is nobody's application, so it does not invent one in the count.
    expect(folder.applications).toBe(0);
  });

  /*
   * A copy that fails once must not disown the file for ever.
   *
   * `landed` is pushed to after the copy, and the manifest was rewritten from
   * `landed` alone — so a name whose copy threw was left out of both halves of
   * it, and the next sync, finding the file still on disk with nothing
   * claiming it, read it as a file of the user's and refused to touch it. For
   * ever: never re-copied, never deleted, and no longer offered to the
   * extension. One `EBUSY` from a PDF open in a viewer is enough, and the
   * folder then holds yesterday's document under exactly the right name.
   *
   * A directory in the way is the same failure with a cause that can be
   * arranged: the sync refuses to copy over something that is not a file, and
   * says so.
   */
  it('keeps hold of a document whose copy failed, and puts it there next time', async () => {
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('t') }).expect(200);
    const dir = syncCurrent(t.store).dir;

    // Take it back out and leave something in the way that cannot be written
    // over, so this sync's copy throws.
    fs.rmSync(path.join(dir, 'Transcript.pdf'), { force: true });
    fs.mkdirSync(path.join(dir, 'Transcript.pdf'), { recursive: true });
    const refused = syncCurrent(t.store);
    expect(refused.files).not.toContain('Transcript.pdf');
    expect((refused.problems ?? []).join(' ')).toContain('Transcript.pdf');

    /*
     * And now the state a real failure leaves: the name is there, holding the
     * old copy, because the rename never happened. A directory is only the
     * device for making the copy throw on demand — what is being asked is
     * what the manifest remembers afterwards, and the answer has to be "this
     * one is still mine" rather than "somebody else's file is in the way".
     */
    fs.rmSync(path.join(dir, 'Transcript.pdf'), { recursive: true, force: true });
    fs.writeFileSync(path.join(dir, 'Transcript.pdf'), 'the copy that never got replaced');
    const after = syncCurrent(t.store);
    expect((after.problems ?? []).join(' ')).not.toContain('Transcript.pdf');
    expect(after.files).toContain('Transcript.pdf');
    // And the stale copy really was replaced, not merely tolerated.
    expect(fs.readFileSync(path.join(dir, 'Transcript.pdf'), 'utf8')).not.toContain('never got replaced');
  });

  /*
   * And the other half of owning it: taking it away again.
   *
   * The manifest's list of files is "what is here and correct", which a copy
   * that failed is not — so the delete loop, reading that list, never knew
   * the stale copy was the folder's to remove. Delete the document and it
   * stayed, under exactly the name an upload dialog is pointed at, with
   * nothing in the panel mentioning it.
   */
  it('takes away a stale copy of a document, even one whose copy had failed', async () => {
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('t') }).expect(200);
    const dir = syncCurrent(t.store).dir;
    const at = path.join(dir, 'Transcript.pdf');

    // A copy that fails, leaving the old file where it was.
    fs.rmSync(at, { force: true });
    fs.mkdirSync(at, { recursive: true });
    syncCurrent(t.store);
    fs.rmSync(at, { recursive: true, force: true });
    fs.writeFileSync(at, 'the copy that never got replaced');

    await request(app).delete('/api/documents/Transcript.pdf').expect(200);
    const after = syncCurrent(t.store);
    expect(after.files).not.toContain('Transcript.pdf');
    expect(fs.existsSync(at)).toBe(false);
  });

  /*
   * The same names every other file in the save is held to.
   *
   * This was the one write in the store that went straight to
   * `writeFileSync`, so a document skipped the checks the rest of the class
   * argues for at length. A save is a git repository meant to be cloned onto
   * other machines, and a colon in a filename stops a Windows checkout
   * partway through — on a name the user picked by dragging a file in.
   */
  it('refuses a document name the save could not be cloned with', async () => {
    const said = await request(app)
      .post('/api/documents')
      .send({ name: 'Transcript: Fall 2024.pdf', data: pdf('t') })
      .expect(400);
    expect(said.body.error).toMatch(/not a name this save can hold/i);
  });

  /*
   * And a dotted name says why it is a dotted name.
   *
   * Going through `writeAtomic` refuses this one anyway, as an unportable
   * name — so this is about the sentence rather than the outcome. It is worth
   * its own: `listDocuments` skips anything beginning with a dot because the
   * manifest and the scratch files look like that, and somebody who dragged
   * in `.transcript.pdf` is owed that reason rather than a paragraph about
   * cloning onto Windows. Before the write went through `writeAtomic` at all,
   * the file was written, committed, and then unlistable for ever.
   */
  it('refuses a name beginning with a dot, which it could never list again', async () => {
    const said = await request(app)
      .post('/api/documents')
      .send({ name: '.transcript.pdf', data: pdf('t') })
      .expect(400);
    expect(said.body.error).toMatch(/begins with a dot/i);
    const listed = await request(app).get('/api/documents').expect(200);
    expect(listed.body.documents.map((d: { name: string }) => d.name)).not.toContain('.transcript.pdf');
  });

  /*
   * And when the copy into the upload folder does not happen, the panel is
   * told. A file of the user's already holding that name means the document
   * is in the save and nowhere anything can attach it from — which came back
   * as a plain 200 under the words "ready to attach".
   */
  it('says so when the upload folder would not take it', async () => {
    // Something of the user's, already in the folder under that name.
    const dir = syncCurrent(t.store).dir;
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'Transcript.pdf'), 'the one I polished myself');

    const added = await request(app)
      .post('/api/documents')
      .send({ name: 'Transcript.pdf', data: pdf('t') })
      .expect(200);
    expect((added.body.problems ?? []).join(' ')).toMatch(/Transcript\.pdf/);
    // And the user's own file is still theirs.
    expect(fs.readFileSync(path.join(dir, 'Transcript.pdf'), 'utf8')).toContain('polished myself');
  });

  it('takes it out of the folder again when it is removed', async () => {
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('t') }).expect(200);
    expect(syncCurrent(t.store).files).toContain('Transcript.pdf');

    await request(app).delete('/api/documents/Transcript.pdf').expect(200);
    const after = syncCurrent(t.store);
    expect(after.files).not.toContain('Transcript.pdf');
    expect(fs.existsSync(path.join(after.dir, 'Transcript.pdf'))).toBe(false);
  });

  it('refuses a name that is a path, like every other name in the save', async () => {
    const refused = await request(app)
      .post('/api/documents')
      .send({ name: '../config.yaml', data: pdf('not this') })
      .expect(400);
    expect(refused.body.error).toMatch(/not allowed/i);
    expect(t.store.loadConfig().ai).toBeDefined();
  });

  it('says plainly when a document is not there', async () => {
    const missing = await request(app).get('/api/documents/Nothing.pdf/file').expect(404);
    expect(missing.body.error).toMatch(/not in this save/i);
  });

  it('saving the same name again replaces it, which is how renaming works', async () => {
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('old') }).expect(200);
    await request(app).post('/api/documents').send({ name: 'Transcript.pdf', data: pdf('new') }).expect(200);
    expect(t.store.listDocuments()).toHaveLength(1);
    expect(t.store.readDocument('Transcript.pdf')?.toString()).toContain('new');
  });
});
